name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd ./submission
        docker build . --file Dockerfile --tag panaani/logbook:latest
        docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
        docker push $DOCKER_USERNAME/logbook:latest
